export const KEY_LOCALSTORAGE_PLAYER_ID = "KEY_LOCALSTORAGE_PLAYER_ID";
export const KEY_LOCALSTORAGE_PLAYER_NAME = "KEY_LOCALSTORAGE_PLAYER_NAME";

export const EVENT_CREATE_PLAYER = "EVENT_CREATE_PLAYER";
export const EVENT_RENAME_PLAYER = "EVENT_RENAME_PLAYER";

export const EVENT_CREATE_ROOM = "EVENT_CREATE_ROOM";
export const EVENT_ROOM_LIST = "EVENT_ROOM_LIST";
export const EVENT_ENTER_HALL = "EVENT_ENTER_HALL";
export const EVENT_JOIN_ROOM = "EVENT_JOIN_ROOM";
export const EVENT_LEAVE_ROOM = "EVENT_LEAVE_ROOM";
export const EVENT_ADD_PLAYER = "EVENT_ADD_PLAYER";
export const EVENT_REMOVE_PLAYER = "EVENT_REMOVE_PLAYER";
export const EVENT_PLAYER_LIST = "EVENT_PLAYER_LIST";

export const EVENT_ENTER_GAME = "EVENT_ENTER_GAME";