export const KEY_LOCALSTORAGE_PLAYER_ID = "KEY_LOCALSTORAGE_PLAYER_ID";
export const KEY_LOCALSTORAGE_PLAYER_NICK = "KEY_LOCALSTORAGE_PLAYER_NICK";

export const EVENT_CREATE_ROOM = "EVENT_CREATE_ROOM";
export const EVENT_ROOM_LIST = "EVENT_ROOM_LIST";
export const EVENT_ENTER_HALL = "EVENT_ENTER_HALL";
export const EVENT_JOIN_ROOM = "EVENT_JOIN_ROOM";
export const EVENT_LEAVE_ROOM = "EVENT_LEAVE_ROOM";
export const EVENT_ENTER_GAME = "EVENT_ENTER_GAME";